osx_image: xcode9.1
language: objective-c
script:
- pod install --project-directory=Example
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/HDDelegateButton.xcworkspace -scheme HDDelegateButton-Example -sdk iphonesimulator11.1 -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.1' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
notifications:
  email: false
  slack:
    secure: k6ZPS0TJkK3k9DyRLN/nuIdOzbI3e8RteHmAaXYFpbIfjh9JEGA4f75sj1hxvv6hpLeO5nvkX7bodOjyIgdR8h9U5xT2UXJ2P4pxJNfurTkfMCMKv2DG+uSrU7d1E5U3y4R3NHo84zoexP0YGem5AmC0npW0SyYR/FUG0u2oGqbRbUAop3IB9En4ZURnX4G8KlxYR6uazTm3/2Pj1N+bgv+X4PXS0EWE3RZ75+9N5UWRahwABfo2lDt711Hwzfn3ulwK+uqroq+MawR5I8PUrTMYY28dPogxC7XZ4sQz/2s0GJhPIMgBGX3fY8PVqagfO4uR+upFkEzszPibTsytLe87TNVQibsnACDU1Gd3W7M0JNvG0jwjYjKj3KiKlULFm3PsAlujEFysALx1RKpDjARkJh63QkG1joM1wd6Xa5SxuXrr0SRfANgkzH7htlMvgaollLwLxzCSXzr/Di2zoEV74Vqo+Pn0b0GjxeaodBNZIMGItQ7ieUpHsnXJesFrQzNRuS1XJ1Z1qDRV+GPjxl0cFRbuT51ttd2aYkYUiaA9ObgI4WoFEQL41BZOVUB+yKYrznl33LD6DxhhYhMYzaX8b0obgb/o34X1qc3u/eV6ToGkfwnsovMpxOTI03wNCAIDoow4YxDZN0BSsWdk+EFBd9YbhdBvIYsBSje/KnE=
